---
title: "0-screenCalibration"
author: "Will Sheppard"
date: "2024-05-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

this scrip will read the screen calibration data from a screen.

this will contain the RGB value for each color and the luminance in cd/m^2

the values need to be compared to a Gamma curve and a measure of error calculate

```{r libraries}

requiredPackages = c("tidyverse", "readr", "stringr")
for(p in requiredPackages){
  if(!require(p,character.only = TRUE)) install.packages(p)
  library(p,character.only = TRUE)
}

```


```{r datasets}


allData <- read.csv("C:/Users/cn13ws/OneDrive - University of Leeds/screenCalibration/drivingLabPcAll.csv") %>%
  mutate(L = 0.2126*RGB + 0.7152*RGB + 0.0722*RGB)




```

```{r initial plot}


allData %>%
  ggplot(aes(x = RGB, y = lumMean)) +
  geom_point()#+
  #geom_smooth(aes(x = RGB, y = lumMean),
  #              method = "glm", method.args = list(family = "Gamma"),
  #            se = F)
  
```
