---
title: "dataSim"
output: html_document
date: "2022-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r readDF}
df <- read.csv("../pilotData/outputDF.csv")

```


find means and sds for chart tests nad differences between chart and online/lab
```{r mns}
#cs chart mean and sd
csM <- mean(df$csChart)
csS <- sd(df$csChart)

csLs <- sd(df$csLab)
csOs <- sd(df$csOnline)

# va chart mean and sd
vaM <- mean(df$vaChart)
vaS <- sd(df$vaChart)

vaLs <- sd(df$vaLab)
vaOs <- sd(df$vaOnline)

### these are not being currently used, was an old idea byt cba delteing and rewiring code if i am wrong
# cs diff mean and sd
cs_CL_M <- mean(df$csChart-df$csLab)
cs_CL_S <- sd(df$csChart-df$csLab)
cs_CO_M <- mean(df$csChart-df$csOnline)
cs_CO_S <- sd(df$csChart-df$csOnline)

# va diff mean and sd
va_CL_M <- mean(df$vaChart-df$vaLab)
va_CL_S <- sd(df$vaChart-df$vaLab)
va_CO_M <- mean(df$vaChart-df$vaOnline)
va_CO_S <- sd(df$vaChart-df$vaOnline)



```

```{r df sim}
dfSim <- data.frame(csChart = rnorm(n = 100, mean = csM, sd = csS),
                    vaChart = rnorm(n = 100, mean = vaM, sd = vaS))
library(tidyverse)

dfSim <- dfSim %>%
  mutate(csLab = rnorm(n = 100, mean = csChart, sd = csLs),
         csOnline = rnorm(n = 100, mean = csChart, sd = csOs),
         vaLab = rnorm(n = 100, mean = vaChart, sd = vaLs),
         vaOnline = rnorm(n = 100, mean = vaChart, sd = vaOs))
```

save data
```{r save}
write.csv(dfSim, "../pilotData/simDF.csv")
```