---
title: "rtDeepdive"
output: html_document
date: "2022-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## R Markdown


```{r load packages}
library(blandr)
library(ggplot2)
library(psych)
```

## read data
i have simmed 100 particiapnts from the 4 pilot data sets
```{r read data, echo=FALSE}
df <- read.csv("../data/thresholdDF.csv")
```

```{r distributions}
ggplot(df)+
  geom_density(aes(x = csOnline, colour = 'red', fill = 'red'), alpha = 0.5)+
  geom_density(aes(x = csLab, colour = 'blue', fill = 'blue'), alpha = 0.5)#+
  #geom_density(aes(x = csChart, colour = 'green', fill = 'green'), alpha = 0.5)

ggplot(df)+
  geom_density(aes(x = vaOnline, colour = 'red', fill = 'red'), alpha = 0.5)+
  geom_density(aes(x = vaLab, colour = 'blue', fill = 'blue'), alpha = 0.5)#+
  #geom_density(aes(x = vaChart, colour = 'green', fill = 'green'), alpha = 0.5)

ggplot(df)+
  geom_density(aes(x = csOnlineRT, colour = 'red', fill = 'red'), alpha = 0.5)+
  geom_density(aes(x = csLabRT, colour = 'blue', fill = 'blue'), alpha = 0.5)

ggplot(df)+
  geom_density(aes(x = vaOnlineRT, colour = 'red', fill = 'red'), alpha = 0.5)+
  geom_density(aes(x = vaLabRT, colour = 'blue', fill = 'blue'), alpha = 0.5)
```


```{r rt v thresh}
ggplot(df, aes(x = csOnlineRT, y = csOnline))+
  geom_point()+
  geom_smooth(method = lm)

ggplot(df, aes(x = csLabRT, y = csLab))+
  geom_point()+
  geom_smooth(method = lm)

ggplot(df, aes(x = vaOnlineRT, y = vaOnline))+
  geom_point()+
  geom_smooth(method = lm)

ggplot(df, aes(x = vaLabRT, y = vaLab))+
  geom_point()+
  geom_smooth(method = lm)
```

```{r within person}

csThresh <- df %>%
  select(id, csLab, csOnline)%>%
  pivot_longer(!id, names_to = 'test', values_to = 'thresh')

csRT <- df %>%
  select(id, csLabRT, csOnlineRT)%>%
  pivot_longer(!id, names_to = 'test', values_to = 'thresh')

ggplot(csThresh, aes(x = test, y = thresh))+
  geom_boxplot()

ggplot(csRT, aes(x = thresh, color = test))+
  geom_density()

t.test(df$csLab, df$csOnline, paired = T, alternative = 'two.sided')
t.test(df$vaLab, df$vaOnline, paired = T, alternative = 'two.sided')

t.test(df$csLabRT, df$csOnlineRT, paired = T, alternative = 'two.sided')
t.test(df$vaLabRT, df$vaOnlineRT, paired = T, alternative = 'two.sided')

```