---
title: "thresholdIntersection"
output: html_document
date: "2022-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
import some data
```{r import data}
csLab <- read.csv('../data/csSummLab.csv')
csLab$id <- as.factor(csLab$id)

csOnline <- read.csv('../data/csSummOnline.csv')
csOnline$id <- as.factor(csOnline$id)

vaLab <- read.csv('../data/vaSummLab.csv')
vaLab$id <- as.factor(vaLab$id)

vaOnline <- read.csv('../data/csSummOnline.csv')
vaOnline$id <- as.factor(vaOnline$id)

chart <- read.csv('../data/visualTestData.csv') 
chart$id <- as.factor(chart$id)

#remove blank rows
chart <- chart[complete.cases(chart), ]
```

```{r binomial smooth funciton}
binomial_smooth = function(link='probit', ...){
  geom_smooth(method = 'glm', 
              method.args = list(family=binomial(link=link)), ...)
}
```


plot cs lab data
```{r cs lab plots}
csLabPP <- unique(csLab$id)
#csLabPP <- 1

for (pp in csLabPP) {
  x <- csLab %>%
    filter(id == pp)
  
  rowInd <- which(chart$id == pp)
  colInd <- grep("csChart", colnames(chart))
  
  rowCS <- chart[rowInd, colInd]
  
  #print(rowCS)
  
  p <- ggplot(x, aes(x = contrast, y = percCorrect))+
  geom_point() + 
    binomial_smooth(span = 0.1)+
  #stat_smooth(span = 0.75)+
    geom_vline(xintercept = rowCS)+
    scale_x_continuous(limits = c(0,10), breaks = seq(0, 10, by = 1))+
    scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, by = 0.1))
  
  show(p)
  
}


```