---
title: "vaCategorisation"
author: "Will Sheppard"
date: "2023-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(blandr)
library(tidyverse)
library(psych)
```

## read data
i have simmed 100 particiapnts from the 4 pilot data sets
```{r read data, echo=FALSE}
df <- read.csv("../data/vaThreshClean.csv")%>%
  select(-contains("RT", ignore.case = F))%>%
  select(id, contains('va'))

```

```{r set categories}

dfCat <- df %>%
  mutate(chartCat = case_when(
    vaChart >= 1 ~ 5,
    vaChart < 1 & vaChart >= 0.5 ~ 4,
    vaChart < 0.5 & vaChart >= 0.3 ~ 3,
    vaChart < 0.3 & vaChart >= 0.0 ~ 2,
    vaChart < 0.0 ~ 1),
    onlineCat = case_when(
    vaOnline >= 1 ~ 5,
    vaOnline < 1 & vaOnline >= 0.5 ~ 4,
    vaOnline < 0.5 & vaOnline >= 0.3 ~ 3,
    vaOnline < 0.3 & vaOnline >= 0.0 ~ 2,
    vaOnline < 0.0 ~ 1),
    labCat = case_when(
    vaLab >= 1 ~ 5,
    vaLab < 1 & vaLab >= 0.5 ~ 4,
    vaLab < 0.5 & vaLab >= 0.3 ~ 3,
    vaLab < 0.3 & vaLab >= 0.0 ~ 2,
    vaLab < 0.0 ~ 1),
  )%>%
  select(contains('cat'))

```


```{r agreement}
dfAgree <- dfCat %>%
  mutate(chart_online = case_when(
    chartCat == onlineCat ~ 1,
    chartCat != onlineCat ~ 0
  ),
  chart_lab = case_when(
    chartCat == labCat ~ 1,
    chartCat != labCat ~ 0),
  lab_online = case_when(
    labCat == onlineCat ~ 1,
    labCat != onlineCat ~ 0
  )
  )%>%
  select(-ends_with('Cat'))%>%
  summarise(chart_onlinePerc = mean(chart_online),
            chart_labPerc = mean(chart_lab),
            lab_onlinePerc = mean(lab_online))
```

```{r graphs}
dfChart <- dfCat %>%
  pivot_longer(cols = ends_with('Cat'), names_to = 'method', values_to = 'cat')%>%
  mutate(method = case_when(
    method == "chartCat" ~ "Clinical",
    method == "labCat" ~ "Online Semi-Supervised",
    method == "onlineCat" ~ "Online Unsupervised"
  ))

vaCat <- ggplot(dfChart, aes(x = as.factor(cat)))+
  geom_bar()+
  facet_grid(~method)+ 
  scale_x_discrete(breaks = c("1", "2", "3", "4", "5", "6"),
                   labels = c("B", "F", "Mild", "Mod", "S", "Blind"))+ 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r save plots}

h = 10
w = h*1.4
ggsave("../figures/vaCat.png", plot = vaCat, dpi = 800,units = 'cm', height = h, width = w)
```